### ISSUE TITLE
chidren need more care

### ISSUE THREAD

**Issue by newsiberian** [vazco/meteor-universe-react-grid-layout#1]
Hello, 
The package are really awesome. Many thanks for porting it:), but,
I'm stuck with getting this package work.
I've tried to run your examples  from component created via React.createClass and via React.component and always get the same results.

Instead of having [here](https://github.com/STRML/react-grid-layout/blob/0d366bcf16aa00643748fb970a5bb5db72dfba65/lib/utils.js#L322) good result like this:
![grid_good](https://cloud.githubusercontent.com/assets/11130487/10709387/77f1b616-7a45-11e5-96be-39104df474bb.jpeg)

My children array always looks like here:
![grid_bad](https://cloud.githubusercontent.com/assets/11130487/10709389/8e8b4284-7a45-11e5-97a7-d2d48a44ea74.jpeg)

**Comment by cristo-rabani** [comment]
Hello, 
Do You use ResponsiveReactGridLayout or pure ReactGridLayout.

ResponsiveReactGridLayout doesn't work correctly. Maybe this is by other version of react.
But now, you can try to get this component by importing it, directly from npm using universe:modules-npm (https://www.npmjs.com/package/react-grid-layout)

Maybe It's is already fixed by author of this package.
(If you will tried import from npm and everything will be work correctly, let us know about this. )

**Comment by newsiberian** [comment]
Thanks you.
I had a problem with Responsive. After that I've tried ReactGridLayout too. I've took your code almost 'as it is' from README and it's also failed.

I will try to grub package from npm.

**Comment by newsiberian** [comment]
I found the explanation. I got such a strange children array, because I'm wrap a component in Radium.

I apologize for the fact that you are distracted.

**Comment by newsiberian** [comment]
I have few more questions.
About your package:
- following code works almost fine:
```
<ResponsiveReactGridLayout
        className="layout"
        layouts={ layouts }
        breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
        cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }}
      >
        <div key={1} _grid={{x: 0, y: 0, w: 1, h: 2}}>1</div>
        <div key={2} _grid={{x: 1, y: 0, w: 1, h: 2}}>2</div>
        <div key={3} _grid={{x: 2, y: 0, w: 1, h: 2}}>3</div>
      </ResponsiveReactGridLayout>
```
but something more complex, like this:
```
      <ResponsiveReactGridLayout
        className="layout"
        layouts={ layouts }
        breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
        cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }}
      >
        { products.map((product) => {
          return <ProductGridItem
            key={ product._id }
            data={ product }
            />
        }) }
      </ResponsiveReactGridLayout>
```
throws:
```
TypeError: Cannot read property 'resetState' of undefined
    at React.createClass.componentWillReceiveProps (universe_react-grid-layout.js:926)
    at ReactCompositeComponentMixin.updateComponent (react.browserify.js:7195)
    at wrapper [as updateComponent] (react.browserify.js:13941)
    at ReactCompositeComponentMixin.receiveComponent (react.browserify.js:7082)
    at Object.ReactReconciler.receiveComponent (react.browserify.js:14817)
    at ReactCompositeComponentMixin._updateRenderedComponent (react.browserify.js:7324)
    at ReactCompositeComponentMixin._performComponentUpdate (react.browserify.js:7302)
    at ReactCompositeComponentMixin.updateComponent (react.browserify.js:7218)
    at wrapper [as updateComponent] (react.browserify.js:13941)
    at ReactCompositeComponentMixin.receiveComponent (react.browserify.js:7082)
```
**this.ref** is clear object in universe_react-grid-layout.js:926

about npm version:
- Do you have any idea how to get access to ResponsiveReactGridLayout via npm?
I tried:

`import {ResponsiveReactGridLayout} from '/myPackages/react-grid-layout/lib/ResponsiveReactGridLayout'
`

or
`import ResponsiveReactGridLayout from '/myPackages/react-grid-layout/lib/ResponsiveReactGridLayout'
`

or
`import {ResponsiveReactGridLayout} from '/myPackages/react-grid-layout'
`

or
`import ResponsiveReactGridLayout from '/myPackages/react-grid-layout'
`

In the last case I have an object but inside it was a ReactGridLayout:(

**Comment by newsiberian** [comment]
I forwarded these questions to the package author [here](https://github.com/STRML/react-grid-layout/issues/120) and [here](https://github.com/STRML/react-grid-layout/issues/121)

**Comment by cristo-rabani** [comment]
in `STRML/react-grid-layout` they have `var ResponsiveReactGridLayout = require('react-grid-layout').Responsive;`

So, in your case it will be:
```
import ResponsiveReactGridLayout from '/myPackages/react-grid-layout/Responsive' 
```

/myPackages/ -this part is the path to file myPackages.npm.json
 
react-grid-layout/ - this part is the name of package from file ( myPackages.npm.json )

eg.
```
{
  "packages" : {
      "react-grid-layout" : "0.9.2"
  }
}
```

last part is path definied inside npm package

**Comment by newsiberian** [comment]
Hello, Thank you for the clarification. It is now clear where does the last part of the path, but yet this method does not work for me:
component: `import ResponsiveReactGridLayout from '/myPackages/react-grid-layout/Responsive'`
package file: `"react-grid-layout" : "0.8.5"` -- because it is the last in npm repo

```
Uncaught (in promise) Error: Module react-grid-layout/Responsive not declared as a dependency.
```

**Comment by cristo-rabani** [comment]
Hello,
try this way:
```
import {Responsive} from '/myPackages/react-grid-layout';
```

0.8.5 is much older then it is used in our meteor package.

2015-10-25 16:58 GMT+01:00 newsiberian <notifications@github.com>:

**Comment by newsiberian** [comment]
import {Responsive} from '/myPackages/react-grid-layout';
or
import Responsive from '/myPackages/react-grid-layout';
=>
Uncaught TypeError: type.toUpperCase is not a function

**Comment by newsiberian** [comment]
Last message was my internal error.
`import {Responsive} from '/myPackages/react-grid-layout';` really works) thank you for your time.

**Comment by cristo-rabani** [comment]
So let me know.
if responsive grid layout works better
 if it's imported by universe:modules-npm

2015-10-25 17:42 GMT+01:00 newsiberian <notifications@github.com>:

**Comment by newsiberian** [comment]
From the first view 'Resizable' bugged on your version. So, yes, npm version is better currently.
