### ISSUE TITLE
How is this supposed to work?

### ISSUE THREAD

**Issue by elie222** [vazco/meteor-universe-react-grid-layout#2]
Copying and pasting code from the documentation into my app gives this error:
`Uncaught SyntaxError: Unexpected token import`

**Comment by cristo-rabani** [comment]
This package works with universe:modules

**Comment by elie222** [comment]
Thanks. So is there a reason it isn't a dependency?

**Comment by cristo-rabani** [comment]
Hello,
actually no there isn't.
but this package should work with universe:ecmascript instead of universe:modules

If you want you can add "api.imply" for modules package and send me pull request
